name: authorization_manager
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com
repository: https://github.com/odroe/authorization_manager

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  json_annotation: ^4.4.0

dev_dependencies:
  build_runner: ^2.1.8
  json_serializable: ^6.1.5
  lints: ^1.0.0
